name: Release Charts

on:
  push:
    branches:
      - '*'

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        run: |
          helm template ./charts/my-test-app
          helm package ./charts/my-test-app

      - name: Upload Helm Charts
        uses: svenstaro/upload-release-action@v2
        with:
          file:  "./charts/my-test-app/*.tgz"
          tag: ${{ github.ref }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v4.0.0
        with:
          includeOpen: true
          ignorePreReleases: true
          failOnError: true
          fetchViaCommits: true
          fetchReviewers: true
          fetchReleaseInformation: true
          fetchReviews: true
          commitMode: true
          exportCache: true
          exportOnly: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}